-- Table: `admin` 管理员表
CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `login_name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '登录名',
  `password` CHAR(32) NOT NULL DEFAULT '' COMMENT '加密后的登录密码',
  `salt` CHAR(6) NOT NULL DEFAULT '' COMMENT '密码加密盐值',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态[0:正常,1:禁用]',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `login_name` (`login_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '管理员表';

-- Table: `user` 用户表
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `login_name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '登录名',
  `password` CHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
  `salt` CHAR(6) NOT NULL DEFAULT '' COMMENT '盐',
  `status` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '状态[0:正常,1:禁用]',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户表';

-- Table: `user_profile` 用户个人信息表
CREATE TABLE IF NOT EXISTS `user_profile` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `user_id` INT(10) UNSIGNED NOT NULL COMMENT 'FK:user id',
  `sex` TINYINT(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '性别[1:男,2:女]',
  `phone` CHAR(11) NOT NULL DEFAULT '' COMMENT '手机号码',
  `avatar` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户头像地址',
  `real_name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `email` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '邮箱',
  `idcard` CHAR(18) NOT NULL DEFAULT '' COMMENT '身份证',
  `qq` VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'QQ号码',
  `reg_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '注册时间',
  `reg_ip` VARCHAR(15) NOT NULL DEFAULT 0 COMMENT '注册IP',
  `last_login_time` INT(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最后登录时间',
  `last_login_ip` VARCHAR(15) NOT NULL DEFAULT 0 COMMENT '最后登录IP',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户个人信息表';

-- Table: `keywords` 关键字词汇表
CREATE TABLE IF NOT EXISTS `keywords` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `type` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '类型[1:广告法,2:会员地址,3:旺旺ID,4:手机号码]',
  `word` VARCHAR(600) NOT NULL DEFAULT '' COMMENT '关键词',
  `status` TINYINT(4) NOT NULL DEFAULT 0 COMMENT  '状态:[0:正常]',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `word` (`word`),
  KEY `type` (`type`),
  KEY `deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '关键字词汇表';

-- Table: `article` 文章表
CREATE TABLE IF NOT EXISTS `article` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `created_id` INT(10) UNSIGNED NOT NULL COMMENT '创建者(FK:user id)',
  `delete_id` INT(10) UNSIGNED DEFAULT NULL COMMENT '删除人(FK:admin user id)',
  `cid` INT(10) UNSIGNED NOT NULL COMMENT '所属类型id[1:日本,2:韩国3:欧美]',
  `title` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '标题',
  `subtitle` VARCHAR(255) DEFAULT '' COMMENT '短标题',
  `pic` VARCHAR(255) DEFAULT NULL COMMENT '缩略图',
  `source` VARCHAR(255) DEFAULT NULL COMMENT '来源[1:后台录入,2:网上抄袭]',
  `author` VARCHAR(20) DEFAULT NULL COMMENT '作者',
  `resume` VARCHAR(500) DEFAULT NULL COMMENT '摘要,描述',
  `pub_date` INT(10) NOT NULL DEFAULT 0 COMMENT '发表日期',
  `content` TEXT COMMENT '文章内容',
  `hits` INT(11) NOT NULL DEFAULT 0 COMMENT '点击次数',
  `status` TINYINT(4) NOT NULL DEFAULT 0 COMMENT '状态[0:正常]',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `created_id` (`created_id`),
  KEY `delete_id` (`delete_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='文章表';

-- TABLE: `detection_apply_info` 检测权限申请信息表
CREATE TABLE IF NOT EXISTS `detection_apply_info` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `user_id` INT(10) UNSIGNED NOT NULL COMMENT 'FK:user id',
  `phone` VARCHAR(11) NOT NULL DEFAULT '' COMMENT '电话',
  `qq` VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'qq',
  `email` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'E-Mail',
  `apply_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '申请时间',
  `status` TINYINT(4) NOT NULL DEFAULT 0 COMMENT  '状态:[0:正常]',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '检测权限申请信息表';

-- TABLE: `leave_message` 留言信息表
CREATE TABLE IF NOT EXISTS `leave_message` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `user_id` INT(10) UNSIGNED NOT NULL COMMENT 'FK:user id',
  `phone` VARCHAR(11) NOT NULL DEFAULT '' COMMENT '电话',
  `qq` VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'qq',
  `email` VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'E-Mail',
  `leave_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '留言时间',
  `content` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT '留言内容',
  `status` TINYINT(4) NOT NULL DEFAULT 0 COMMENT  '状态:[0:正常]',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '留言信息表';

-- TABLE: `dict_area` 国家地区字典表
CREATE TABLE IF NOT EXISTS `dict_area` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `pid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父ID',
  `level` TINYINT NOT NULL DEFAULT 1 COMMENT '区域级别[1:省,2:市,3:县]',
  `name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '地区名称',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态[0:正常].',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `pid` (`pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '国家地区字典表';

-- TABLE: `address_keywords` 地址关键字词汇表
CREATE TABLE IF NOT EXISTS `address_keywords` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `province_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'FK:dict_area id 省份ID',
  `city_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'FK:dict_area id 市区ID',
  `county_id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'FK:dict_area id 县城ID',
  `address` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '详细地址',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态[0:正常].',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `province_city_county` (`province_id`, `city_id`, `county_id`),
  KEY `address` (`address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '地址关键字词汇表';

-- TABLE: `banner` banner地址表
CREATE TABLE IF NOT EXISTS `banner` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `img_path` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '图片路径',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '状态[0:启用,1:禁用].',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '删除时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'banner地址表';
